### ISSUE TITLE
Error on relativePositionToAbsolutePosition (local)

### ISSUE THREAD

**Issue by estebanprimost** [y-js/y-prosemirror#1]
Hi @dmonad, excellent work with this binding!. We are trying to start testing it and can't run demo locally because of next error:

```
y-prosemirror.js:297 Uncaught TypeError: Cannot read property 'constructor' of undefined
    at relativePositionToAbsolutePosition (y-prosemirror.js:297)
    at y-prosemirror.js:407
    at ProsemirrorBinding.mux (mutex.js:29)
    at ProsemirrorBinding._typeChanged (y-prosemirror.js:398)
    at callAll (function.js:11)
    at callEventHandlerListeners (yjs.mjs:341)
    at yjs.mjs:1058
    at Map.forEach (<anonymous>)
    at transact (yjs.mjs:1047)
    at Doc.transact (yjs.mjs:1200)
```

Steps to reproduce:
```bash
git clone git@github.com:y-js/yjs-demos.git
cd yjs-demos
yarn
yarn start

Go to `ProseMirror Binding` and start typing.
```

This demo is working perfectly on [your live site](https://yjs-demos.now.sh/prosemirror/). 

Thanks in advance!

**Comment by dmonad** [comment]
Hey @estebanprimost 
Make sure that you are running the same Yjs/y-prosemirror version as in the [yjs-demos](https://github.com/y-js/yjs-demos) repository. We currently have:

    "yjs": "^13.0.0-84"
    "y-prosemirror": "0.0.3",

I recently made a breaking change to Yjs. I'll close this ticket when I upgraded y-prosemirror to work with current Yjs.

**Comment by estebanprimost** [comment]
Thanks @dmonad. I didn't see the `package-lock.json` and I've testing it with `yarn`. Now it works. Thanks.

**Comment by dmonad** [comment]
I also updated the example and the y-prosemirror binding.
